@startuml
top to bottom direction

state Création
state HorsStock
state EnPromotion
state Commande
state Approvisionnement
state Supprimé
state Obsolète
state Annulation

[*] -d-> Création : Produit ajouté au catalogue
Création -d-> EnStock : Stock initial

EnStock -d-> HorsStock : Stock épuisé
EnStock -l-> EnPromotion : Promotion activée
EnPromotion --> EnStock : Promotion terminée

EnStock --> Commande : Commande effectuée
Commande --> EnStock : Retirer produit du stock
Commande --> HorsStock : Stock insuffisant
Commande --> Annulation : Commande annulée

Approvisionnement -l-> EnStock : Réapprovisionnement effectué

HorsStock --> Supprimé : Produit supprimé
HorsStock --> Approvisionnement : Produit recommandé
HorsStock --> EnPromotion : Promotion sur produit épuisé
Supprimé --> EnStock : Réintroduction produit
Supprimé --> Obsolète : Produit définitivement arrêté

Annulation --> EnStock : Produit restocké



Obsolète --> [*] : Fin définitive

@enduml
