@startuml
top to bottom direction
[*] --> EnStock : Produit ajouté

EnStock --> EnPromotion : Promotion activée
EnStock --> HorsStock : Stock épuisé

EnPromotion --> EnStock : Promotion terminée
EnPromotion --> HorsStock : Stock épuisé

HorsStock --> Supprimé : Produit supprimé
HorsStock --> Recommande : Produit recommandé

Recommande --> EnStock : Réapprovisionnement effectué

Supprimé --> [*] : Fin du cycle
@enduml

