@startuml
left to right direction

actor Administrateur as Admin
actor Utilisateur as User

rectangle "Gestion des comptes utilisateur" {
    usecase "Validation d'un compte" as UC1
    usecase "Radiation d'un compte" as UC2
    usecase "Réinitialisation du mot de passe" as UC3
    usecase "Authentification" as UC4
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
User --> UC3

UC3 ..> UC4 :<<include>>
UC2 ..> UC4 :<<include>>

@enduml
