@startuml
left to right direction
actor Utilisateur as User
actor Admin as Admin

rectangle "Gestion de Profil" {
    usecase "Changer Avatar" as UC6
    usecase "Modifier information de son compte (sauf adresse mail)" as UC7
    usecase "Être authentifié" as UC9
    usecase "Modifier un compte utilisateur (sauf adresse mail)" as UC8
}
Admin --|> User

User --> UC6
User --> UC7
UC6 ..> UC9 : <<include>>
UC7 ..> UC9 : <<include>>

Admin --> UC8
UC8 ..> UC9 : <<include>>

@enduml