@startuml
left to right direction
actor User
actor Admin
rectangle "Accès au site" {

    usecase "compte valide" as UC2
    usecase "se connecter" as UC3
    usecase "gestion des comptes utilisateurs" as UC4

    usecase "Changer Avatar" as UC6
    usecase "authantitification" as UC7
}

User --> UC3
UC3 ..> UC2 : <<include>>
UC3 ..> UC7 : <<include>>
Admin --> UC3
UC3 <.. UC6 : <<extend>>
Admin --> UC4
UC4 ..>UC3 : <<include>>


@enduml
