@startuml

class Boutique {
}

abstract class Compte <<abstract>> {
    - int id
    - String email
    - String motDePasse
    - String nom
    - String prenom
    - String avatar
}

interface Client <<interface>>{
}

class Utilisateur {
    - int id
    - String adressePostale
    - String telephone
}

class Visiteur {
}

class Administrateur {
    - int id
}

class Produit {
    - int id
    - String nom
    - String description
    - double prix
    - int stock
}

class Commande {
    - int id
    - String numeroCommande
    - Date dateCommande
    - String statut
}

class Panier {
    - int id
    - int numeroPanier
}

class Categorie {
    - int id
    - String nom
}

'------------------------------------------------
'Relations

class Note {
    - int id
    - int noteSatisfaction
    - String commentaire
}

class Message {
    - int id
    - String message
    - String contactEmail
}

'------------------------------------------------
' Noms d'associations
'Y a des espaces pour aligner les noms

' Boutique gère plusieurs comptes
Boutique "0..*  " -- "1  " Compte : "gère"

' Boutique contient plusieurs commandes
Boutique "0..*" -- "1     " Commande : " contient"

' Boutique regroupe plusieurs catégories
Boutique "0..*" -- "1" Categorie : " regroupe"

' Boutique propose plusieurs produits
Boutique "0..*" -- "     1" Produit : " propose"

' Héritage / spécialisation
Administrateur --|> Compte
Utilisateur --|> Compte

' Implémentation de l'interface Client
Visiteur ..|> Client
Utilisateur ..|> Client

' Un produit peut appartenir à plusieurs catégories, et vice versa
Produit "*" -- "*" Categorie : "appartient"

' Un panier (0..1) peut contenir plusieurs produits
Panier "0..1 " -- "\t* " Produit : " contient"

' Une commande (1) est liée à un panier (0..1)
Commande "1" -- "0..1" Panier : " est liée à"

' Une commande est passée par plusieurs utilisateurs éventuels (ou un)
Commande "1 " -- "0..* " Utilisateur : " passe"

' Un client possède un ou plusieurs paniers
Client "0..*" -- "1  " Panier : "possède\n"

' Plusieurs notes pour un même produit
Produit "0..* " -- "1 " Note : " note"

' Un compte est lié à une messagerie
Message "1" --> "1\n" Compte : "associée à"

@enduml
